### ISSUE TITLE
Broken JSON responses

### ISSUE THREAD

**Issue by patrickschaper** [luyadev/luya-headless#25]
### What steps will reproduce the problem?
https://demo.luya.io/en/admin/login
Log in as admin and check XHR responses.

### What is the expected result?
Valid JSON

### What do you get instead? (A Screenshot can help us a lot!)
Invalid JSON always starting with `)]}',`

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
Problem is in any version.
Using docker version with nginx, so no apache modules
1: [ini_get('short_open_tag')] ''
2: [ini_get('error_reporting')] '32767'
3: [phpversion()] '7.2.17'
4: [php_ini_loaded_file()] false
5: [php_sapi_name()] 'fpm-fcgi'
6: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'nginx/1.17.2'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  Kickstarter 1.0.6 with core 1.0.20, headless 2.3.0, module-admin 2.1.0, bootstrap 1.0.5, composer 1.0.5, generic 1.0.4
| PHP Version      | 7.2.17
| Platform         | Docker with luyadev/luya-docker-php, mysql:5.7, nginx:latest
| Operating system | OSX

**Comment by nadar** [comment]
This is an expected behavior, its called "json cruft" and makes the admin more secure (https://github.com/luyadev/luya/issues/1789). You can either disable this behavior or (even better) you can remove the cruft before transform your response into json, there is a header: `x-cruft-length` which contains the lenght of the prepend cruft. Here you can see how the luya headless package handles this: https://github.com/luyadev/luya-headless/blob/master/src/collectors/CurlRequestClient.php#L112-L128

**Comment by patrickschaper** [comment]
Thanks for the fast response. If it's a security feature then, of course, I'll remove it on reception.

**Comment by nadar** [comment]
So i can close i assume?
